import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { getGitState } from './git';
import { findContextDir, findProjectRoot } from './utils/contextFinder';

export interface PackOptions {
    short?: boolean;
}

export function sanitizeInlineMarkdown(val: string): string {
    return val.replace(/[`\r\n]/g, ' ').replace(/\s+/g, ' ').trim();
}

function parseFrontmatterValue(content: string, key: string): string {
    const fmMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!fmMatch) return '';
    const safeKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const match = fmMatch[1].match(new RegExp(`^${safeKey}:\\s*["']?([^"'\\r\\n]+)["']?`, 'm'));
    return match ? match[1].trim() : '';
}

export function getCurrentContextRevision(contextDir: string): string {
    const readFileSafe = (relPath: string) => {
        const full = path.join(contextDir, relPath);
        return fs.existsSync(full) ? fs.readFileSync(full, 'utf-8').replace(/\r\n?/g, '\n').trim() : '';
    };

    const projectContent = readFileSafe('project.md');
    const requirementsContent = readFileSafe('requirements.md');
    const stateContent = readFileSafe('state.md');
    const glossaryContent = readFileSafe('glossary.md');
    const decisionsDir = path.join(contextDir, 'decisions');
    const decisions: string[] = [];

    if (fs.existsSync(decisionsDir)) {
        const files = (fs.readdirSync(decisionsDir) as string[]).filter(f => f.endsWith('.md')).sort();
        for (const f of files) {
            decisions.push(fs.readFileSync(path.join(decisionsDir, f), 'utf-8').replace(/\r\n?/g, '\n').trim());
        }
    }

    const rawStateBlob = projectContent + requirementsContent + stateContent + glossaryContent + decisions.join('');
    return crypto.createHash('sha256').update(rawStateBlob).digest('hex').substring(0, 16);
}

export function composeContext(cwd: string = process.cwd(), options: PackOptions = {}): string {
    const contextDir = findContextDir(cwd);
    const projectRoot = findProjectRoot(cwd);

    const readFileSafe = (relPath: string) => {
        const full = path.join(contextDir, relPath);
        return fs.existsSync(full) ? fs.readFileSync(full, 'utf-8').replace(/\r\n?/g, '\n').trim() : '';
    };

    const projectContent = readFileSafe('project.md');
    const requirementsContent = readFileSafe('requirements.md');
    const stateContent = readFileSafe('state.md');
    const glossaryContent = readFileSafe('glossary.md');

    const decisionsDir = path.join(contextDir, 'decisions');
    const activeDecisions: string[] = [];
    const supersededDecisions: string[] = [];

    if (fs.existsSync(decisionsDir)) {
        const files = (fs.readdirSync(decisionsDir) as string[]).filter(f => f.endsWith('.md'));
        for (const f of files) {
            const content = fs.readFileSync(path.join(decisionsDir, f), 'utf-8').replace(/\r\n?/g, '\n').trim();
            const status = parseFrontmatterValue(content, 'status') || 'active';
            const id = parseFrontmatterValue(content, 'id') || f.replace('.md', '');
            const title = parseFrontmatterValue(content, 'title') || 'Untitled Decision';

            if (status.toLowerCase() === 'active') {
                activeDecisions.push(content);
            } else if (status.toLowerCase() === 'superseded') {
                supersededDecisions.push(`- **[${id}] ${title}** *(Superseded / Obsolete)*`);
            }
        }
    }

    const git = getGitState(projectRoot);
    const contextRevisionHash = getCurrentContextRevision(contextDir);

    let out = `<!-- CONTEXT PACK: AUTOMATICALLY GENERATED BY PACTX [rev: ${contextRevisionHash}] -->\n\n`;
    out += `You are acting as the Tech Lead / Senior Software Engineer for this project.\n`;
    out += `Read the canonical state below before making decisions or generating code.\n\n`;

    if (projectContent) {
        out += `### 1. PROJECT & INVARIANTS\n${projectContent}\n\n`;
    }

    if (requirementsContent) {
        const reqBody = requirementsContent.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/, '').trim();
        if (reqBody) {
            out += `### 2. REQUIREMENTS & BUSINESS RULES\n${reqBody}\n\n`;
        }
    }

    if (stateContent) {
        out += `### 3. CURRENT STATE & ACTIVE TASK\n${stateContent}\n\n`;
    }

    if (activeDecisions.length > 0) {
        out += `### 4. ACTIVE ARCHITECTURAL DECISIONS (ADRs)\n`;
        out += activeDecisions.join('\n---\n') + `\n\n`;
    }

    if (supersededDecisions.length > 0 && !options.short) {
        out += `### SUPERSEDED DECISIONS (DO NOT FOLLOW):\n`;
        out += supersededDecisions.join('\n') + `\n\n`;
    }

    if (glossaryContent && !options.short) {
        out += `### 5. GLOSSARY & CONTRACTS\n${glossaryContent}\n\n`;
    }

    if (git.isGit) {
        out += `### 6. RUNTIME & LOCAL REPOSITORY\n`;
        out += `- **Active Git Branch:** \`${sanitizeInlineMarkdown(git.branch || 'detached')}\`\n`;
        if (git.recentCommits.length > 0) {
            out += `- **Recent Commits:**\n  ` + git.recentCommits.map((c: string) => `* ${sanitizeInlineMarkdown(c)}`).join('\n  ') + `\n`;
        }
        if (git.modifiedFiles.length > 0) {
            out += `- **Locally Modified Files:**\n  ` + git.modifiedFiles.slice(0, 10).map((m: string) => `* \`${sanitizeInlineMarkdown(m)}\``).join('\n  ') + `\n`;
        }
        out += `\n`;
    }

    out += `### CANONICAL HANDOFF & SHUTDOWN PROTOCOL:\n`;
    out += `When completing a task, making decisions, or when the user requests "/handoff", emit the structured block below.\n`;
    out += `GUIDELINES: Record ONLY actual facts and decisions established in this session. NEVER invent decisions to fill the schema. If no decisions were made, use empty arrays ([]).\n\n`;
    out += `\`\`\`pactx-update\n`;
    out += `version: "1.1"\n`;
    out += `base_revision: "${contextRevisionHash}"\n`;
    out += `state:\n`;
    out += `  active_task: "<active task name>"\n`;
    out += `  status: "IN_PROGRESS | BLOCKED | COMPLETED"\n`;
    out += `  recommended_model: "Medium | High"\n`;
    out += `  completed_items:\n    - "<completed item>"\n`;
    out += `  new_facts:\n    - "<proven runtime fact or discovery>"\n`;
    out += `  rejected_hypotheses:\n    - "<tested and disproven hypothesis>"\n`;
    out += `  next_action: "<immediate next action>"\n`;
    out += `new_requirements: []\n`;
    out += `new_decisions: []\n`;
    out += `superseded_decisions: []\n`;
    out += `new_glossary_terms: []\n`;
    out += `\`\`\`\n`;

    return out;
}